config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.urls.base import reverse_lazy, reverse
from django.views import defaults as default_views
from allauth.account.views import PasswordChangeView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
    #     "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # Your stuff: custom urls includes go here
    # path("reprohack/", include("reprohack_hub.urls", namespace="reprohack")),
    path("", include("reprohack_hub.urls")),
    re_path(r'^markdownx/', include('markdownx.urls')),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

reprohack_hub/urls.py
from allauth.account.views import PasswordChangeView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings
from .models import Event
from .views import (EventCreate, EventUpdate, EventDetail, EventList, IndexView,
                    PaperCreate, PaperUpdate, PaperDetail, PaperList,
                    ReviewCreate, ReviewDetail, ReviewUpdate, ReviewList, RedirectView,
                    UserDetailView, UserUpdateView, UserRedirectView, MarkdownView,
                    UserSearchEndpointView, PaperTagSearchEndpointView, UserEditRedirectView, UserDeleteView)


urlpatterns = [
    # User management
    path("accounts/", include("allauth.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('resources',
         MarkdownView.as_view(extra_context={'title': 'Resources',
                                             'markdown_file': 'resources.md'}),
         name='resources'),
    path('ways-to-reprohack',
         MarkdownView.as_view(extra_context={'title': 'Ways to ReproHack!',
                                             'markdown_file': 'ways-to-reprohack.md'}),
         name='ways-to-reprohack'),
    path('faq',
         MarkdownView.as_view(extra_context={'title': 'Frequently Asked Questions',
                                             'markdown_file': 'faq.md'}),
         name='faq'),
    path('participant_guidelines',
         MarkdownView.as_view(extra_context={'title': 'Participant Guidelines',
                                             'markdown_file': 'participant_guidelines.md'}),
         name='participant_guidelines'),
    path('organiser_guidelines',
         MarkdownView.as_view(extra_context={'title': 'Organiser Guidelines',
                                             'markdown_file': 'organiser_guidelines.md'}),
         name='organiser_guidelines'),
    path('author_guidelines',
         MarkdownView.as_view(extra_context={'title': 'Author Guidelines',
                                             'markdown_file': 'author_guidelines.md'}),
         name='author_guidelines'),
    path('code-of-conduct',
         MarkdownView.as_view(extra_context={'title': 'Code of Conduct',
                                             'markdown_file': 'code-of-conduct.md'}),
         name='code-of-conduct'),
    path('data_protection_and_privacy_policy',
         MarkdownView.as_view(extra_context={'title': 'Data Protection & Privacy Policy',
                                             'markdown_file': 'data_protection_and_privacy_policy.md'}),
         name='data_protection_and_privacy_policy'),
    path('hackpad_template',
         MarkdownView.as_view(extra_context={'title': 'HackMD Hackpad Template',
                                             'markdown_file': 'templates/hackpad-hackmd-template.md'}),
         name='hackpad_template'),
    path('intro_slides_template',
         MarkdownView.as_view(extra_context={'title': 'HackMD Introductory Slides Template',
                                             'markdown_file': 'templates/intro-slides-hackmd-template.md'}),
         name='intro_slides_template'),
    path("user_redirect/", view=UserRedirectView.as_view(), name="user_redirect"),
    path("user_edit_redirect/", view=UserEditRedirectView.as_view(), name="user_edit_redirect"),
    path('users/<str:username>/', UserDetailView.as_view(), name='user_detail'),
    path('users/<str:username>/edit/',
         UserUpdateView.as_view(), name='user_update'),
    path('users/<str:username>/delete/',
         UserDeleteView.as_view(), name='user_delete'),
    path("user_search", view=UserSearchEndpointView.as_view()),
    path('', IndexView.as_view(), name='index'),
    path('', IndexView.as_view(), name='home'),
    path('event/', EventList.as_view(), name='event_list'),
    path('event/<int:pk>/', EventDetail.as_view(), name='event_detail'),
    path('event/<int:pk>/edit/', EventUpdate.as_view(), name='event_edit'),
    path('event/new/', EventCreate.as_view(), name='event_new'),
    path('paper/', PaperList.as_view(), name='paper_list'),
    path('paper/<int:pk>/', PaperDetail.as_view(), name='paper_detail'),
    path('paper/<int:pk>/edit/', PaperUpdate.as_view(), name='paper_edit'),
    path('paper/new/', PaperCreate.as_view(), name='paper_new'),
    path('paper/tags_search/', PaperTagSearchEndpointView.as_view(),
         name='paper_tags_search'),
    path('review/', ReviewList.as_view(), name="review_list"),
    path('review/new', ReviewCreate.as_view(), name="review_new"),
    path('review/new/<int:paperid>', ReviewCreate.as_view(), name="review_new"),
    path('review/<int:pk>/', ReviewDetail.as_view(), name="review_detail"),
    path('review/<int:pk>/edit/', ReviewUpdate.as_view(), name="review_edit"),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('about', TemplateView.as_view(
        template_name='about.html'), name='about'),
    	 path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/reprohack_favicons/favicon.ico'))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reprohack_hub/models.py
"""
ReproHack Venue, Event, Author, Paper and Review models.

Todo:
    * Check if default submission_date for Event and Paper is redundant.
"""

from datetime import datetime, timedelta
from typing import Any, Tuple, Dict

from django.contrib.auth import get_user_model
from django.db.models.query_utils import Q
from django_countries.fields import CountryField

from markdownx.models import MarkdownxField

from timezone_field import TimeZoneField

from taggit.managers import TaggableManager

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import include, re_path, reverse
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.db import models
from django.contrib.auth.models import AbstractUser, AnonymousUser
from django.db.models import CharField
from django.conf import settings

from django.db.models.signals import post_save
from django.dispatch import receiver

import os

from reprohack_hub.utils import next_x_hour

from allauth.account.decorators import verified_email_required
RATING_MIN = 0
RATING_MAX = 10
RATING_DEFAULT = 10

DEFAULT_EVENT_START_HOUR = 10
DEFAULT_EVENT_END_HOUR = 16


# class Venue(models.Model):
#
#     """Venue with spatial coordinates.
#
#     To ensure this is likely to be user faced, users should only see Venues
#     related to Events they create.
#     """
#
#     # id = models.AutoField(primary_key=True)
#     # creator = models.ForeignKey(User, on_delete=models.CASCADE)
#     detail = models.CharField(_('Eg: Room #'), max_length=300)
#     address1 = models.CharField(max_length=200)
#     address2 = models.CharField(max_length=200)
#     city = models.CharField(max_length=60)
#     postcode = models.CharField(max_length=15)
#     country = models.CharField(max_length=60)
#     geom = models.PointField(blank=True, null=True)
#
#     def __str__(self):
#         return self.name
#
#     # def get_absolute_url(self):
#     #     return reverse('venue_detail', args=[self.id])
class User(AbstractUser):
    """Default user for ReproHack Hub.

    Todo:
        * Consider Surname and Other (first, middle etc.) names
    """

    #: First and last name do not cover name patterns around the globe
    full_name = CharField(_("Your full name"), null=True, blank=False, max_length=255)
    preferred_name = CharField(_("What should we call you?"), null=True, blank=False, max_length=255)
    email = CharField(_("E-mail"), blank=False, unique=True, max_length=255)
    bio = models.TextField(max_length=500, blank=True)
    affiliation = models.CharField(max_length=70, blank=True)
    location = models.CharField(max_length=70, blank=True)
    twitter = models.CharField(max_length=15, blank=True)
    github = models.CharField(max_length=39, blank=True)
    orcid = models.CharField(max_length=19, blank=True)
    consent = models.BooleanField(_("I have read and accept the Data Protection & Privacy Policy"), default = False)

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("user_detail", kwargs={"username": self.username})

    def get_related_events(self):
        return self.created_events.all()

    def get_related_papers(self):
        return self.submitted_papers.all()

    def get_related_reviews(self):
        related_reviews = []
        for paper_reviewer in self.paperreviewer_set.all():
            related_reviews.append(paper_reviewer.review)

        return related_reviews

    def delete(self, using=None, keep_parents=False):

        # Archive all user's papers
        for paper in self.submitted_papers.all():
            paper.archive = True
            paper.save()

        # Make someone else lead reviewer
        for paperreviewer in self.paperreviewer_set.all():
            if paperreviewer.lead_reviewer:
                paperreviewer.lead_reviewer = False
                paperreviewer.save()  # Make user not lead reviewer
                review = paperreviewer.review

                # Make first other user in the set a lead reviewer
                for prv in review.paperreviewer_set.all():
                    if prv.user.pk != self.pk:
                        prv.lead_reviewer = True
                        prv.save()
                        break


        return super().delete(using, keep_parents)


def default_event_start(hour: int = DEFAULT_EVENT_START_HOUR) -> datetime:
    """Return next default start time."""
    return next_x_hour(hour)


def default_event_end(hour: int = DEFAULT_EVENT_END_HOUR) -> datetime:
    """Return next default start time."""
    return next_x_hour(hour, default_event_start())


def get_default_description():
    description_file = open(os.path.join(settings.STATIC_ROOT,
                                         'txt/event-description-default.md'))
    description_text = description_file.read()
    description_file.close()
    return description_text


class Event(models.Model):

    """An event to organise reproducing Paper results.

    Todo:
        * Consider UUIDs for URLs
        * Consider Venue Model separate to Event
        * Auto-set to locale of user at point of login
    """

    # id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="created_events")
    host = models.CharField(max_length=200)
    title = models.CharField(_('Event Title'), max_length=200)
    contact_email = models.EmailField(null=True, blank=True)
    # time
    # date = models.DateField(default=date.today)
    start_time = models.DateTimeField(default=default_event_start)
    end_time = models.DateTimeField(default=default_event_end)
    time_zone = TimeZoneField(default='Europe/London')
    remote = models.BooleanField(default=False)

    # location
    # venue = models.ForeignKey(Venue, on_delete=models.SET_NULL, null=True)
    description = MarkdownxField(_('Feel free to customise provided template'),
                                 default=get_default_description,
                                 help_text=mark_safe("Markdown field. See <a href='https://daringfireball.net/projects/markdown/syntax'> full documentation of supported syntax</a>" ))
    # location = models.CharField(max_length=200)  # Location name?
    address1 = models.CharField(max_length=200, blank=True)
    address2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=60, blank=True)
    postcode = models.CharField(max_length=15, blank=True)
    country = CountryField(blank=True)
    registration_url = models.URLField(blank=True)
    hackpad_url = models.URLField(blank=True, help_text=mark_safe("See our hackmd.io <a href='/hackpad_template'> Event Hackpad Template</a>"))
    slides_url = models.URLField(blank=True, help_text=mark_safe("See our hackmd.io <a href='/intro_slides_template'> Introductory Slides Template</a>"))
    event_coordinates = models.TextField(blank=True, null=True)
    is_initial_upload = models.BooleanField(default=False)

    submission_date = models.DateTimeField(auto_now_add=True)
    # remote = models.BooleanField(default=False)

    # def submit(self):
    #     self.submission_date = get_time_zone.now()
    #     self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('event_detail', args=[self.id])

    @ property
    def re_path(self):
        return self.get_absolute_url()

    @ property
    def address(self):
        addr_items = [self.address1, self.address2,
                      self.city, self.postcode, self.country.name]

        used_addr_items = []
        for addr_item in addr_items:
            if addr_item and isinstance(addr_item, str) and len(addr_item.strip()) > 0:
                used_addr_items.append(addr_item.strip())

        return ", ".join(used_addr_items)

    @ property
    def lat(self):
        return self.decompress_lat_long(0)

    @ property
    def long(self):
        return self.decompress_lat_long(1)

    def decompress_lat_long(self, decompressed_value_index):
        if self.event_coordinates:
            lat_long_split = self.event_coordinates.split(",")
            if len(lat_long_split) > 1:
                return lat_long_split[decompressed_value_index]

        return None

# ---- Papers ---- #
def limit_paper_event_choices():
    return {'start_time__gte': timezone.now()}

class Paper(models.Model):

    class ReviewAvailability(models.TextChoices):
        ALL = 'ALL', _('Available for review at any event')
        EVENT_ONLY = 'EVT_ONLY', _(
            'Only available for review at associated event')

    """A paper to reproduce.

    Todo:
        * Consider UUIDs for url
        * Consider clarifying submission_date (date paper is
          submitted to journal vs added to this database)
        * Could test DOI with https://github.com/fabiobatalha/crossrefapi
        * Consider shifting contact boolean to AuthorsAndSubmitters
    """

    title = models.TextField(_("Paper Title"))
    authors = models.TextField(
        _("Paper Authors"),
        help_text=_("Please separate authors names with commas"))
    event = models.ForeignKey(Event, help_text=_("Associated Event (leave blank if general submission)"), null=True, blank=True,
                              on_delete=models.SET_NULL, limit_choices_to = limit_paper_event_choices)

    citation_txt = models.TextField(_(
        "Reference"), max_length=1000,
        help_text=_("Full reference of the paper in text format"))
    doi = models.CharField(_("DOI (eg. 10.1000/xyz123)"),
                           max_length=200, null=True, blank=True)
    description = models.TextField(
        _("Short Description of the paper"), max_length=2000,

reprohack_hub/templates/event/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% load deleted_user %}
{% load markdown_tags %}

{% block content %}

<div class="bradcam_area breadcam_bg overlay2">
  <h1>
    {{ event.title }}
    {% if user.pk == event.creator.pk %}
    <a class="btn btn-default" href="{% url 'event_edit' pk=event.pk %}"><i class="bi-pencil"></i> </a>
    {% endif %}

  </h1>
</div>
<div class="whole-wrap">
  <div class="container box_1170">
    <div class="section-top-border">
      <div class="event">
        <div class="card-box" style="">
          <div class="card-body">
            <div class="row">
              <div class="col-md-9">
                <h3 class="card-title"> {{ event.title }} </h3>
                <h4 class="card-title"><i class="fa fa-calendar">&nbsp;&nbsp;<i class="bi-clock"></i>
                    &nbsp;&nbsp; </i>{{ event.start_time }} - {{ event.end_time }} ({{ event.time_zone}})</h4>
                {% if event.remote %}
                <h5 class="card-title"><i class="fas fa-globe"></i> &nbsp;&nbsp; Remote
                </h5>
                {% else %}
                <h5 class="card-title"><i class="fa fa-map-pin"></i> &nbsp;&nbsp; {{ event.address }}
                </h5>
                {% endif %}
                <p class="card-text">
                  {% if event.host %}
                  <h5>Hosted by: {{ event.host}}</h5>
                  {% endif%}
                </p>
                <br>
                <h6 class="card-subtitle mb-2 text-muted">Event submitted by:
                  {% if event.creator %}
                  <a href="{{ event.creator.get_absolute_url }}">{{ event.creator.username }}</a>
                  {% else %}
                  {% deleted_user %}
                  {% endif %}
                  on {{ event.submission_date }}
                </h6>
              </div>
              <div class="col-md-3" style="align:center;">
                <br>
                {% if event.registration_url %}
                <a href={{ event.registration_url }} class="boxed_btn_orange2" style="font-size: 1.5em;">
                  Register
                </a>
                {% endif%}
                <br>
                <br>
                <a href="https://reprohack-autoinvite.herokuapp.com/">
                  <img src="https://img.shields.io/badge/slack-join%20us-orange?style=for-the-badge&logo=slack" />
                </a>
                <div class="contact-box">
                  <a href="mailto:{{event.contact_email}}">
                    <i class="fas fa-envelope-square"></i> Contact Host
                  </a>
                  <br>
                  {% if event.hackpad_url %}
                  <a href={{ event.hackpad_url }}>
                    <i class="far fa-edit"></i></i> Hackpad
                  </a>
                  {% endif %}
                  {% if event.slides_url %}
                  <br>
                  <a href={{ event.slides_url }}>
                    <i class="far fa-play-circle"></i></i> Slides
                  </a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="event-description">
          <h3> Event Description </h3>
          <p>{{ event.description | show_markdown | safe }}</p>

          {% if not event.remote %}
          {% include "event/event_map_single.html" %}
          {% endif %}

          <h2>Associated papers</h2>
          {% if event.paper_set.count > 0 %}
          <ul>
            {% for paper in event.paper_set.all %}
            {% if not paper.archive %}
            <li class="paper card-box">
              <h3><a href="{{ paper.get_absolute_url }}">{{ paper.title }}</a></h3>
              <h5>Authors: {{ paper.authors }}</h5>
              <h5>DOI: &nbsp;<a href="https://www.doi.org/{{ paper.doi }}">{{ paper.doi }}</a></h5>
              <h5>Submitted by <a href="{{ paper.submitter.get_absolute_url }}">{{ paper.submitter.username }}</a>
                <span class="icon-box">
                  {%  if paper.event %} &nbsp; <i class="fas fa-calendar-day"></i> {% endif %}
                  {%  if paper.review_availability == "ALL" %} &nbsp; <i class="far fa-list-alt"></i>
                  {% endif %}
                  {%  if paper.public_reviews %} &nbsp; <i class="fas fa-globe-africa"></i> {% endif %}
                </span>
              </h5>
              {% if paper.num_reviews > 0 %}
              <span class="paper-metric">
                <strong> <i class="fas fa-check-circle"></i> &nbsp; Mean reproducibility score: </strong> &nbsp;
                {{ paper.mean_reproducibility_score | floatformat:1 }}/10
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <strong><i class="fas fa-recycle"></i> Number of reviews: </strong> &nbsp;
                {{ paper.num_reviews }}
              </span>
              {% endif %}
              <hr>
              <small>
                <strong> Why should we attempt to reproduce this paper? </strong>
                <p>{{ paper.why }}</p>
              </small>

              <div class="detail_text">
                <span class="detail_header">Tags:</span>
                {% for tag in paper.tags.all %}
                <a href="/paper/?tags={{ tag }}" class="badge badge-primary p-1 m-1">{{ tag }}</a>
                {% endfor %}
              </div>
            </li>
            {% endif %}
            {% endfor %}
          </ul>
          {% else %}
          No associated papers

          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reprohack_hub/templates/event/event_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<script>
  function Hide() {
    if (document.getElementById('id_remote').checked) {
      document.getElementById('div_id_address1').style.display = 'none';
      document.getElementById('div_id_address2').style.display = 'none';
      document.getElementById('div_id_city').style.display = 'none';
      document.getElementById('div_id_postcode').style.display = 'none';
      document.getElementById('div_id_country').style.display = 'none';
      document.getElementById('div_id_event_coordinates').style.display = 'none';
    } else {
      document.getElementById('div_id_address1').style.display = '';
      document.getElementById('div_id_address2').style.display = '';
      document.getElementById('div_id_city').style.display = '';
      document.getElementById('div_id_postcode').style.display = '';
      document.getElementById('div_id_country').style.display = '';
      document.getElementById('div_id_event_coordinates').style.display = '';
    }
  };

</script>
<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg overlay2">
  <h1>Edit event</h1>
</div>
<div class="whole-wrap">
  <div class="container box_1170">
    <div class="section-top-border">
      <h1>Event details</h1>
    </div>

    <div class="content container">
      <form method="POST" class="event-form" method="POST">
        {% csrf_token %}
        {% crispy form %}
      </form>
    </div>
  </div>

  <script type="text/javascript">
    window.addEventListener("load", Hide);

  </script>
  <script type="text/javascript">
    var el = document.getElementById("div_id_remote");
    el.addEventListener("click", Hide);

  </script>
  {% endblock %}

reprohack_hub/templates/event/event_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="bradcam_area breadcam_bg overlay2">
  <h1>Events</h1>
  <br>
  <br>
  <a href="{% url 'event_new' %}" class="boxed_btn">Submit an event!</a>
</div>
<div class="whole-wrap">
  <div class="container box_1170">
    <div class="section-top-border">
      <div class="row">
        <div class="col-sm-9">
          <br>
          <div class="row">
            <div class="col">
              {% include "event/event_map.html" with object_list=page_object_list %}
            </div>
          </div>
          <br>


          <h1>Upcoming Events</h1>
          <ul>
            {% for event in  upcoming_page.object_list %}
            <li class="event card-box">
              <h3 class="card-title"><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></h3>
              {% if event.remote %}
              <h4><i class="fas fa-globe"></i> &nbsp;&nbsp; Remote </h4>
              {% else %}
              <h4><i class="fa fa-map-pin"></i> &nbsp; {{ event.city }}, {{ event.country }} </h4>
              {% endif %}
              <div class="date">
                <i class="bi-clock"></i>
                {{ event.start_time }} - {{ event.end_time }} (TZ: {{ event.time_zone }})
              </div>
            </li>
            {% endfor %}

          </ul>

          {% include "misc/pagination-2-lists.html" with page_obj=upcoming_page page2_obj=past_page page_var=upcoming_event_query_var page2_var=past_event_query_var %}






          <h1>Past Events</h1>
          {% if not past_page.object_list %}
          No objects
          {% endif %}
          <ul>
            {% for event in past_page.object_list %}
            <li class="event card-box">
              <h3 class="card-title"><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></h3>
              {% if event.remote %}
              <h4><i class="fas fa-globe"></i> &nbsp; Remote </h4>
              {% else %}
              <h4><i class="fa fa-map-pin"></i> &nbsp; {{ event.city }}, {{ event.country }} </h4>
              {% endif %}
              <div class="date">
                <i class="bi-clock"></i>
                {{ event.start_time }} - {{ event.end_time }} (TZ: {{ event.time_zone }})
              </div>
            </li>
            {% endfor %}
          </ul>

          {% include "misc/pagination-2-lists.html" with page_obj=past_page page2_obj=upcoming_page page_var=past_event_query_var page2_var=upcoming_event_query_var%}


        </div>
        <div class="col-sm-3">
          <h4>Search for events</h4>
          <form method="get">
            <div class="mb-4">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search events..." name="search" aria-label="Search"
                  value="{{ search }}" />
                <div class="input-group-append">
                  <button type="submit" class="btn-primary btn"><i class="bi-search m-0 p-0"
                      style="font-size: 0.7em"></i> Search
                  </button>
                </div>
              </div>

            </div>
          </form>

        </div>
      </div>


    </div>
  </div>
</div>
{% endblock %}

reprohack_hub/templates/event/event_map_single.html
<div id="map" style="height: 30rem; width: 100%"></div>
<script>




  $(document).ready(function () {

    var greenMarker = L.AwesomeMarkers.icon({
        icon: 'asterisk',
        markerColor: 'green',
        prefix: 'fa',
        });

    var eventLocations = [
      {% for event in object_list %}
        {% if event.lat and event.long %}
      {
        latlng: L.latLng({{ event.lat }}, {{ event.long }}),
        title: "{{ event.title }}",
        url: "{{ event.url }}",
      },
        {% endif %}
      {% endfor %}
      {% if event and event.lat and event.long %}
        {
        latlng: L.latLng({{ event.lat }}, {{ event.long }}),
        title: "{{ event.title }}",
          url: "{{ event.url }}",
      },
      {% endif %}
    ];

    let eventBounds = null;
    if(eventLocations.length > 1){
      let latlngs = [];
      for(let i in eventLocations){
        latlngs.push(eventLocations[i].latlng);
      }
      eventBounds = L.latLngBounds(latlngs);
    }

    let mapConfig = {
      zoom: 7,
      scrollWheelZoom: false,
    }

    let map = L.map('map', mapConfig);
    if(eventBounds){
      map.fitBounds(eventBounds);
    }
    else if(eventLocations.length > 0){
      map.setView(eventLocations[0].latlng, mapConfig.zoom);
    }
    else{
      map.setView([51.505, -0.09], mapConfig.zoom);
    }

    // Add map layers
    let CartoDB_Positron = L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
        subdomains: 'abcd',
        maxZoom: 19
        }).addTo(map);

    // Add markers
    for(let i in eventLocations){
      let event = eventLocations[i];
      let marker = L.marker(event.latlng, {icon: greenMarker}).addTo(map)
            .bindPopup(`<a href="${event.url}">${event.title}</a>`);
    }

  })
</script>

reprohack_hub/templates/event/event_new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<script>
  function Hide() {
    if (document.getElementById('id_remote').checked) {
      document.getElementById('div_id_address1').style.display = 'none';
      document.getElementById('div_id_address2').style.display = 'none';
      document.getElementById('div_id_city').style.display = 'none';
      document.getElementById('div_id_postcode').style.display = 'none';
      document.getElementById('div_id_country').style.display = 'none';
      document.getElementById('div_id_event_coordinates').style.display = 'none';
    } else {
      document.getElementById('div_id_address1').style.display = '';
      document.getElementById('div_id_address2').style.display = '';
      document.getElementById('div_id_city').style.display = '';
      document.getElementById('div_id_postcode').style.display = '';
      document.getElementById('div_id_country').style.display = '';
      document.getElementById('div_id_event_coordinates').style.display = '';
    }
  };

</script>

<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg overlay2">
  <h1>Submit Event</h1>
</div>
<!-- bradcam_area_end -->
<div class="whole-wrap">
  <div class="container box_1170">
    <div class="section-top-border">
      <h1>Event details</h1>
    </div>

    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          {% block event-form %}
          {% endblock %}
          <div class="event-form" method="POST">
            {% csrf_token %}
            {% crispy form %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.addEventListener("load", Hide);

</script>
<script type="text/javascript">
  var el = document.getElementById("div_id_remote");
  el.addEventListener("click", Hide);

</script>
{% endblock %}